# Generated by Django 5.0.3 on 2024-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0004_course_teachercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='department_id',
            new_name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='Department.teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherCourse',
        ),
    ]
