# Generated by Django 5.0.3 on 2024-05-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0005_rename_department_id_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
