# Generated by Django 5.0.3 on 2024-05-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_rename_teachers_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(through='Department.TeacherCourse', to='Department.teacher'),
        ),
    ]
