# Generated by Django 5.0.3 on 2024-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0007_teachercourse_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(through='Department.TeacherCourse', to='Department.teacher'),
        ),
    ]
